# Generated by Django 2.2.2 on 2019-06-07 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='biding',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publish',
        ),
        migrations.DeleteModel(
            name='Borrow',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='book',
        ),
        migrations.DeleteModel(
            name='Binding',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
